steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/medical-backend:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/medical-backend:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'api-backend',
        '--image=gcr.io/$PROJECT_ID/medical-backend:latest',
        '--region=us-central1',
        '--service-account=api-backend@$PROJECT_ID.iam.gserviceaccount.com',
        '--allow-unauthenticated=false'
      ]
    timeout: "900s"
